name: 'Quant Cloud Environment Sync'
description: 'Syncs data between environments in Quant Cloud'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  api_key:
    description: 'Quant API key'
    required: true
  organization:
    description: 'Quant organisation ID'
    required: true
  app_name:
    description: 'Name of your application'
    required: true
  environment_name:
    description: 'Name for the environment'
    required: true
  base_url:
    description: 'Quant Cloud API URL'
    required: false
    default: 'https://dashboard.quantcdn.io/api/v3'
  source:
    description: 'Name of the source environment'
    required: true
  wait:
    description: 'Whether to wait for the sync to complete'
    required: false
    default: 'false'
  wait_interval:
    description: 'Interval in seconds to wait for the sync to complete'
    required: false
    default: '10'
  max_retries:
    description: 'Maximum number of retries before timing out'
    required: false
    default: '30'
  type:
    description: 'Type of data to sync'
    required: false
    default: 'database'
outputs:
  sync_id:
    description: 'ID of the sync'
  success:
    description: 'Whether the sync was successful'
    value: true
runs:
  using: 'node20'
  main: 'dist/index.js' 