name: Test Create Environment

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create the environment
        uses: ./
        id: create-environment
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          environment_name: 'production'
          app_name: 'clap'
          organization: 'quant'
          base_url: 'https://portal.stage.quantcdn.io/api/v3'
          compose_spec: '{"containers":[{"name":"nginx-container-1","imageReference":{"type":"external","identifier":"nginx:stable-perl"},"essential":true,"portMappings":[{"containerPort":80,"protocol":"tcp"}]},{"name":"mailhog-container-2","imageReference":{"type":"external","identifier":"mailhog/mailhog:latest"},"essential":true,"portMappings":[{"containerPort":8025,"protocol":"tcp"}]}]}'
      - name: Debug Outputs
        run: |
          echo "Environment Name: ${{ steps.create-environment.outputs.environment_name }}"