name: Test Environment Sync

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'The name of the environment to sync to'
        required: true
        default: 'staging'
      source:
        description: 'The name of the source environment'
        required: true
        default: 'production'
      type:
        description: 'The type of data to sync'
        required: true
        default: 'filesystem'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync environment data
        uses: ./
        id: sync-environment
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          environment_name: ${{ inputs.environment_name || 'staging' }}
          source: ${{ inputs.source || 'production' }}
          app_name: 'actions'
          organization: ${{ secrets.QUANT_ORGANIZATION }}
          type: ${{ inputs.type || 'filesystem' }}
          base_url: ${{ secrets.QUANT_BASE_URL }}
          
      - name: Debug Outputs
        run: |
          echo "Sync Success: ${{ steps.sync-environment.outputs.success }}"