name: Test Environment Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync environment data
        uses: ./
        id: sync-environment
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          environment_name: 'staging'
          source: 'production'
          app_name: 'actions-test'
          organization: ${{ secrets.QUANT_ORGANIZATION }}
          type: 'database'
          base_url: ${{ secrets.QUANT_BASE_URL }}
          
      - name: Debug Outputs
        run: |
          echo "Sync Success: ${{ steps.sync-environment.outputs.success }}"